Fix binance symbols_to_pairs usage
Fixes a bug where some times binance pairs endpoint was called before
the first binance call established a connection and initialized the
mapping. Used to manifest with this exception:

```
[14/10/2021 17:40:57 GMT Daylight Time] ERROR rotkehlchen.api.server Exception on /api/1/exchanges/binance/pairs [GET]
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1513, in full_dispatch_request
  File "site-packages\flask\app.py", line 1499, in dispatch_request
  File "site-packages\flask_restful\__init__.py", line 467, in wrapper
  File "site-packages\flask\views.py", line 83, in view
  File "site-packages\flask_restful\__init__.py", line 582, in dispatch_request
  File "rotkehlchen\api\v1\resources.py", line 1834, in get
  File "rotkehlchen\api\rest.py", line 3240, in get_all_binance_pairs
  File "rotkehlchen\exchanges\manager.py", line 296, in get_all_binance_pairs
AttributeError: 'Binance' object has no attribute '_symbols_to_pair'
```