Pin uv in CI
0.6.13 breaks our CI due to

```
[stderr]
      /home/runner/.cache/uv/builds-v0/.tmpVWMMqG/lib/python3.11/site-packages/setuptools_scm/git.py:135:
      UserWarning: "/home/runner/work/rotki/rotki" is shallow and may cause
      errors
        warnings.warn(f'"{wd.path}" is shallow and may cause errors')
      /home/runner/.cache/uv/builds-v0/.tmpVWMMqG/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py:108:
      _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml`
      is still *beta*.
        warnings.warn(msg, _BetaConfiguration)
      error: invalid command 'bdist_wheel'

      hint: This error likely indicates that `rotkehlchen @
      file:///home/runner/work/rotki/rotki` depends on `wheel`, but
      doesn't declare it as a build dependency. If `rotkehlchen @
      file:///home/runner/work/rotki/rotki` is a first-party package,
      consider adding `wheel` to its `build-system.requires`. Otherwise,
      `uv pip install wheel` into the environment and re-run with
      `--no-build-isolation`.
```

Asked the uv team what change makes it break in their side since it is not stated in the changelog

[run all]