Test that loopring's get_balances can get called
The test is due to an error raised by wrong initialization of loopring
module

```
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/api/rest.py", line 314, in _do_query_async
rotki     result = getattr(self, command)(**kwargs)
rotki   File "/home/lefteris/w/rotkehlchen/rotkehlchen/api/rest.py", line 2501, in _eth_module_query
rotki     result = getattr(module_obj, method)(**kwargs)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/utils/mixins/lockable.py", line 43, in wrapper
rotki     with wrappingobj.query_locks_map_lock:
rotki AttributeError: 'Loopring' object has no attribute 'query_locks_map_lock'
rotki 2022-04-23T13:25:14Z <Greenlet "Greenlet-11" at 0x7f6e19764480: <bound method RestAPI._do_query_async of <rotkehlchen.api.rest.RestAPI object at 0x7f6e1aaaad60>>('_eth_module_query', 2, module_name='loopring', method='get_balances', query_specific_balances_before=None, addresses=['0x4066643f04859fa538Ba8EAa906C197c57e4e3e0'])> failed with AttributeError
rotki Traceback (most recent call last):
rotki   File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
rotki   File "/home/lefteris/w/rotkehlchen/rotkehlchen/api/rest.py", line 314, in _do_query_async
rotki     result = getattr(self, command)(**kwargs)
rotki   File "/home/lefteris/w/rotkehlchen/rotkehlchen/api/rest.py", line 466, in _query_all_balances
    result = self.rotkehlchen.query_balances(
rotki   File "/home/lefteris/w/rotkehlchen/rotkehlchen/rotkehlchen.py", line 681, in query_balances
rotki     loopring_balances = self.chain_manager.get_loopring_balances()
rotki   File "/home/lefteris/w/rotkehlchen/rotkehlchen/utils/mixins/cacheable.py", line 97, in wrapper
rotki     result = f(wrappingobj, *args, **kwargs)
rotki   File "/home/lefteris/w/rotkehlchen/rotkehlchen/chain/manager.py", line 1765, in get_loopring_balances
    balances = loopring_module.get_balances(addresses=addresses)
rotki   File "/home/lefteris/w/rotkehlchen/rotkehlchen/utils/mixins/lockable.py", line 43, in wrapper
    with wrappingobj.query_locks_map_lock:
rotki AttributeError: 'Loopring' object has no attribute
'query_locks_map_lock'
```